/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cuni.mff.ufal.morphodita;

public class Morpho {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Morpho(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Morpho obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        morphodita_javaJNI.delete_Morpho(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Morpho load(String fname) {
    long cPtr = morphodita_javaJNI.Morpho_load(fname);
    return (cPtr == 0) ? null : new Morpho(cPtr, true);
  }

  public int analyze(String form, int guesser, TaggedLemmas lemmas) {
    return morphodita_javaJNI.Morpho_analyze(swigCPtr, this, form, guesser, TaggedLemmas.getCPtr(lemmas), lemmas);
  }

  public int generate(String lemma, String tag_wildcard, int guesser, TaggedLemmasForms forms) {
    return morphodita_javaJNI.Morpho_generate(swigCPtr, this, lemma, tag_wildcard, guesser, TaggedLemmasForms.getCPtr(forms), forms);
  }

  public String rawLemma(String lemma) {
    return morphodita_javaJNI.Morpho_rawLemma(swigCPtr, this, lemma);
  }

  public String lemmaId(String lemma) {
    return morphodita_javaJNI.Morpho_lemmaId(swigCPtr, this, lemma);
  }

  public String rawForm(String form) {
    return morphodita_javaJNI.Morpho_rawForm(swigCPtr, this, form);
  }

  public Tokenizer newTokenizer() {
    long cPtr = morphodita_javaJNI.Morpho_newTokenizer(swigCPtr, this);
    return (cPtr == 0) ? null : new Tokenizer(cPtr, true);
  }

  public final static int NO_GUESSER = morphodita_javaJNI.Morpho_NO_GUESSER_get();
  public final static int GUESSER = morphodita_javaJNI.Morpho_GUESSER_get();

}
