/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cuni.mff.ufal.morphodita;

public class Tagger {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Tagger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tagger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        morphodita_javaJNI.delete_Tagger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Tagger load(String fname) {
    long cPtr = morphodita_javaJNI.Tagger_load(fname);
    return (cPtr == 0) ? null : new Tagger(cPtr, true);
  }

  public Morpho getMorpho() {
    long cPtr = morphodita_javaJNI.Tagger_getMorpho(swigCPtr, this);
    return (cPtr == 0) ? null : new Morpho(cPtr, false);
  }

  public void tag(Forms forms, TaggedLemmas tags) {
    morphodita_javaJNI.Tagger_tag(swigCPtr, this, Forms.getCPtr(forms), forms, TaggedLemmas.getCPtr(tags), tags);
  }

  public Tokenizer newTokenizer() {
    long cPtr = morphodita_javaJNI.Tagger_newTokenizer(swigCPtr, this);
    return (cPtr == 0) ? null : new Tokenizer(cPtr, true);
  }

}
