/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cuni.mff.ufal.morphodita;

public class TaggedLemmasForms {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TaggedLemmasForms(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TaggedLemmasForms obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        morphodita_javaJNI.delete_TaggedLemmasForms(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TaggedLemmasForms() {
    this(morphodita_javaJNI.new_TaggedLemmasForms__SWIG_0(), true);
  }

  public TaggedLemmasForms(long n) {
    this(morphodita_javaJNI.new_TaggedLemmasForms__SWIG_1(n), true);
  }

  public long size() {
    return morphodita_javaJNI.TaggedLemmasForms_size(swigCPtr, this);
  }

  public long capacity() {
    return morphodita_javaJNI.TaggedLemmasForms_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    morphodita_javaJNI.TaggedLemmasForms_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return morphodita_javaJNI.TaggedLemmasForms_isEmpty(swigCPtr, this);
  }

  public void clear() {
    morphodita_javaJNI.TaggedLemmasForms_clear(swigCPtr, this);
  }

  public void add(TaggedLemmaForms x) {
    morphodita_javaJNI.TaggedLemmasForms_add(swigCPtr, this, TaggedLemmaForms.getCPtr(x), x);
  }

  public TaggedLemmaForms get(int i) {
    return new TaggedLemmaForms(morphodita_javaJNI.TaggedLemmasForms_get(swigCPtr, this, i), false);
  }

  public void set(int i, TaggedLemmaForms val) {
    morphodita_javaJNI.TaggedLemmasForms_set(swigCPtr, this, i, TaggedLemmaForms.getCPtr(val), val);
  }

}
