/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cuni.mff.ufal.morphodita;

public class TaggedLemmaForms {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TaggedLemmaForms(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TaggedLemmaForms obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        morphodita_javaJNI.delete_TaggedLemmaForms(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLemma(String value) {
    morphodita_javaJNI.TaggedLemmaForms_lemma_set(swigCPtr, this, value);
  }

  public String getLemma() {
    return morphodita_javaJNI.TaggedLemmaForms_lemma_get(swigCPtr, this);
  }

  public void setForms(TaggedForms value) {
    morphodita_javaJNI.TaggedLemmaForms_forms_set(swigCPtr, this, TaggedForms.getCPtr(value), value);
  }

  public TaggedForms getForms() {
    long cPtr = morphodita_javaJNI.TaggedLemmaForms_forms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TaggedForms(cPtr, false);
  }

  public TaggedLemmaForms() {
    this(morphodita_javaJNI.new_TaggedLemmaForms(), true);
  }

}
