/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cuni.mff.ufal.morphodita;

public class TaggedLemma {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TaggedLemma(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TaggedLemma obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        morphodita_javaJNI.delete_TaggedLemma(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLemma(String value) {
    morphodita_javaJNI.TaggedLemma_lemma_set(swigCPtr, this, value);
  }

  public String getLemma() {
    return morphodita_javaJNI.TaggedLemma_lemma_get(swigCPtr, this);
  }

  public void setTag(String value) {
    morphodita_javaJNI.TaggedLemma_tag_set(swigCPtr, this, value);
  }

  public String getTag() {
    return morphodita_javaJNI.TaggedLemma_tag_get(swigCPtr, this);
  }

  public TaggedLemma() {
    this(morphodita_javaJNI.new_TaggedLemma(), true);
  }

}
