@startuml
skinparam componentStyle uml2
'the result looks better in horizontal orientation
left to right direction

'declarations
actor User
actor FileSystem

package validator {
    component Importer
    component Exporter
    component EntityManager
    component AnalysisBroker
    component DBConnector
    component Controller
}

package editor {
    component GraphVizualizer
    component Editor
    component UnDoManager
}

package webService {
    component Server
}

package tagger {
    component Tagger
    component DBConnector as taggerDBConnector
}

'is grapher part of the webservice?
package grapher {
    component Grapher
    component DBConnector as grapherDBConnector
}

package db {
    component DBAdapter
}

database internalDB
database externalDB

'relations
User -- Editor
Editor - Controller
FileSystem - Importer
FileSystem - Exporter
DBConnector - DBAdapter
EntityManager - DBConnector
AnalysisBroker <-> Server : SOAP
Server -- Tagger
taggerDBConnector - DBAdapter
Server -- Grapher
grapherDBConnector - DBAdapter
DBAdapter - internalDB
DBAdapter - externalDB
@enduml