@startuml
skinparam componentStyle uml2
'left to right direction

'declarations
component Client
node WebServer {
	component Servlet
}
node {
	component Analyzer
}
database DB

'relations
Client <-> Servlet : SOAP
Servlet - Analyzer : TCP/IP
Analyzer -- DB

'notes
note bottom of Analyzer
	Bussiness
	logic
end note

@enduml