/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cuni.mff.ufal.nametag;

public class Tokenizer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Tokenizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tokenizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nametagJNI.delete_Tokenizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setText(String text) {
    nametagJNI.Tokenizer_setText(swigCPtr, this, text);
  }

  public boolean nextSentence(Forms forms, TokenRanges tokens) {
    return nametagJNI.Tokenizer_nextSentence(swigCPtr, this, Forms.getCPtr(forms), forms, TokenRanges.getCPtr(tokens), tokens);
  }

}
