/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cuni.mff.ufal.nametag;

public class NamedEntities {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NamedEntities(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NamedEntities obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nametagJNI.delete_NamedEntities(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NamedEntities() {
    this(nametagJNI.new_NamedEntities__SWIG_0(), true);
  }

  public NamedEntities(long n) {
    this(nametagJNI.new_NamedEntities__SWIG_1(n), true);
  }

  public long size() {
    return nametagJNI.NamedEntities_size(swigCPtr, this);
  }

  public long capacity() {
    return nametagJNI.NamedEntities_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nametagJNI.NamedEntities_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nametagJNI.NamedEntities_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nametagJNI.NamedEntities_clear(swigCPtr, this);
  }

  public void add(NamedEntity x) {
    nametagJNI.NamedEntities_add(swigCPtr, this, NamedEntity.getCPtr(x), x);
  }

  public NamedEntity get(int i) {
    return new NamedEntity(nametagJNI.NamedEntities_get(swigCPtr, this, i), false);
  }

  public void set(int i, NamedEntity val) {
    nametagJNI.NamedEntities_set(swigCPtr, this, i, NamedEntity.getCPtr(val), val);
  }

}
