/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cuni.mff.ufal.nametag;

public class TokenRanges {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TokenRanges(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TokenRanges obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nametagJNI.delete_TokenRanges(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TokenRanges() {
    this(nametagJNI.new_TokenRanges__SWIG_0(), true);
  }

  public TokenRanges(long n) {
    this(nametagJNI.new_TokenRanges__SWIG_1(n), true);
  }

  public long size() {
    return nametagJNI.TokenRanges_size(swigCPtr, this);
  }

  public long capacity() {
    return nametagJNI.TokenRanges_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nametagJNI.TokenRanges_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nametagJNI.TokenRanges_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nametagJNI.TokenRanges_clear(swigCPtr, this);
  }

  public void add(TokenRange x) {
    nametagJNI.TokenRanges_add(swigCPtr, this, TokenRange.getCPtr(x), x);
  }

  public TokenRange get(int i) {
    return new TokenRange(nametagJNI.TokenRanges_get(swigCPtr, this, i), false);
  }

  public void set(int i, TokenRange val) {
    nametagJNI.TokenRanges_set(swigCPtr, this, i, TokenRange.getCPtr(val), val);
  }

}
